### ISSUE TITLE
issue starting program

### ISSUE THREAD

**Issue by doctor-birb** [garrett-davidson/pimiibo#14]
whenever i try to start, it says bash: ./pimiibo is a directory
the command i use is: ./pimiibo /path/keyfile.bin  /path/dump.bin

**Comment by command-tab** [comment]
Did you get this figured out? This seems like an issue similar to #15 where you need to run `cd pimiibo` before running the program.

**Comment by doctor-birb** [comment]
Yea Running cd pimiibo helped, thanks!
