### ISSUE TITLE
Make

### ISSUE THREAD

**Issue by suryandibiase** [garrett-davidson/pimiibo#15]
I’m having issues compiling the sources. I’m very new at this and I cannot get the program to compile. Is there a way to check if it is already compiled (I did get to the bottom of the instructions)? Nothing comes up after I install and update the repository and execute the “make” command.
![C62BFB5E-AA0B-41CC-820B-A116C5B89E60](https://user-images.githubusercontent.com/9088069/117580006-a4968e00-b0ed-11eb-840c-9b95a04650ce.png)

**Comment by command-tab** [comment]
It looks like two things:

1) There’s already a directory named `pimiibo`, which I’m assuming is a prior clone
2) You need to `cd pimiibo` before running make so that you’re in the right place

Try these steps:

```
cd pimiibo
git pull
make
```

**Comment by suryandibiase** [comment]
Thank you that helps a lot. Is a different question but do you know I solve this too?![image](https://user-images.githubusercontent.com/9088069/117585337-cc93ea80-b109-11eb-87a3-525c5ee7e468.png)

**Comment by command-tab** [comment]
It looks like you need to first `cd pimiibo` to change your working directory to the pimiibo/ one.

**Comment by suryandibiase** [comment]
Thanks again it did bring me forward but this appears now. (soory if my questions are so basic, really appreciate your help)
![image](https://user-images.githubusercontent.com/9088069/117636675-f46e6700-b178-11eb-8516-78d4e3d3a6ba.png)

**Comment by command-tab** [comment]
That the last error message there stops at the space after "Amiibo" makes me think there's an issue in pimiibo with handling spaces in paths. You did the right thing by quoting the paths, but it seems like it's still not handling them correctly.

A way to work around this would be to move the relevant files to a path without spaces. Here, I move the retail key and the amiibo file into the same directory as the pimiibo program, then run it and pass in those simplified paths:

```
mv "/home/pi/Downloads/Amiibo Bin Dump/key_retail.bin" ./key_retail.bin
mv "/home/pi/Downloads/Amiibo Bin Dump/Animal Crossing/Figures/Isabelle/Isabelle.bin" ./Isabelle.bin
./pimiibo key_retail.bin Isabelle.bin
```

---

Another option would be to rename the directories such that they no longer contain spaces:

```
mv "/home/pi/Downloads/Amiibo Bin Dump" /home/pi/Downloads/Amiibo_Bin_Dump
mv "/home/pi/Downloads/Amiibo_Bin_Dump/Animal Crossing" /home/pi/Downloads/Amiibo_Bin_Dump/Animal_Crossing
```

Then you could run commands like you were before, but with spaces replaced by underscores:

```
./pimiibo /home/pi/Downloads/Amiibo_Bin_Dump/key_retail.bin /home/pi/Downloads/Amiibo_Bin_Dump/Animal_Crossing/Figures/Isabelle/Isabelle.bin
```

**Comment by suryandibiase** [comment]
Thank you. Everything seems to work now.
