### ISSUE TITLE
Read incorrect number of bytes from file:

### ISSUE THREAD

**Issue by punx45** [garrett-davidson/pimiibo#16]
I understand its been a few years since the last issue, i appreciate any help! :D

on run i get the message "Read incorrect number of bytes from file:" for the key_retail.bin

attempting to run this on a clean install of rasberry pi lite bullseye

the key_retail matches the md5 sum in the instructions. im also running with shortened bin file names in the same directory to eliminate issues with long names 

```
crono@devpi:~/amiibo/pimiibo $ ls
amiibo.cpp  amiitool.cpp    linkToTK.bin    nfchandler.h  README.md
amiibo.h    amiitool.h      Makefile        pimiibo
amiitool    key_retail.bin  nfchandler.cpp  pimiibo.cpp
crono@devpi:~/amiibo/pimiibo $ ./pimiibo linkToTK.bin key_retail.bin 
Read incorrect number of bytes from file: key_retail.bin
crono@devpi:~/amiibo/pimiibo $ ls -l key_retail.bin 
-rw-r--r-- 1 crono crono 160 Jan 28 00:59 key_retail.bin
crono@devpi:~/amiibo/pimiibo $ md5sum key_retail.bin 
45fd53569f5765eef9c337bd5172f937  key_retail.bin

```

**Comment by AbandonedCart** [comment]
You added your arguments in the wrong order.

https://github.com/garrett-davidson/pimiibo#usage

./pimiibo **_path-to-key-file_** path-to-amiibo-file

**Comment by punx45** [comment]
> You added your arguments in the wrong order.
> 
> https://github.com/garrett-davidson/pimiibo#usage
> 
> ./pimiibo **_path-to-key-file_** path-to-amiibo-file

thank you i am a dumbass.
